<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [

    //register
    'Username'=>'Usuario',
    'User: '=>'Usuario: ',
    'Password'=>'Contraseña',
    'Do not you remember your password?'=>'¿No recuerdas tu contraseña?',
    'Click here'=>'Haz clic aquí',
    'LOG IN'=>'INICIAR SESION',
    'Do not you have an account? '=>'¿No tienes cuenta? ',
    'Please Sign Up'=>'Por favor regístrate',
    'Status'=>'Estatus',

    'Password Recovery'=>'Recuperación de contraseña',
    'Please fill in your email. A link to reset your password will be sent there.'=>'Por favor complete su correo electrónico. Allí se enviará un enlace para restablecer la contraseña.',
    'Send'=>'Enviar',
    'Are you already registered? Please '=>'¿Ya estas registrado? Por favor ',
    'Log In'=>'Inicia sesión',
    'SIGN UP'=>'REGISTRARSE',
    'Log out'=>'Salir',
    'Profile'=>'Perfil',
    'NOTIFICATIONS'=>'NOTIFICACIONES',
    'Notifications'=>'Notificaciones',
    'All notifications'=>'Todas las notificaciones',
    'User not found'=>'Usuario no encontrado',
    'Incorrect user or password.'=>'Usuario o contraseña incorrecta.',
    'Your token API is invalid'=>'Su token de API no es válido',
    'Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription.'=>'Acceso denegado debido a una clave de suscripción no válida. Asegúrese de proporcionar una clave válida para una suscripción activa.',
    'Token succesfully generated'=>'Token generado con éxito',
    'Thank you for registering. Please check your inbox for the verification email.'=>'Gracias por registrarse. Por favor revise la bandeja de entrada para el correo de verificación.',
    'Check your email and follow the instructions.'=>'Revise su correo y siga las instrucciones.',
    'We are sorry, we can not reset the password for the email address you provided.'=>'Lo sentimos, no podemos restablecer la contraseña de la dirección de correo proporcionada.',
    'New password saved.'=>'Nueva contraseña guardada.',
    'Your email has been confirmed!'=>'¡Su correo ha sido confirmado!',
    'Reset Password'=>'Restablecer contraseña',
    'Please choose your new password:'=>'Por favor elija su nueva contraseña:',
    'Check your email and follow the instructions.'=>'Revise su correo y siga las instrucciones.',
    'Sorry, we are unable to verify the email for the email address provided.'=>'Lo sentimos, no podemos verificar el correo electrónico de la dirección de correo proporcionada.',
    'Sorry, We are unable to verify your account with the provided token.'=>'Lo sentimos, No podemos verificar su cuenta con el token proporcionado.',
    'Thank you for contacting us. We will respond to you as soon as possible.'=>'Gracias por contactarnos. Nosotros responderemos a la mayor brevedad posible.',
    'There was an error sending your message.'=>'Hubo un error al enviar su mensaje.',
    
    //email text
    'Hello'=>'Hola',
    'Follow the link below to verify your email:'=>'Siga el siguiente enlace para verificar su correo electrónico:',
    'Follow the link below to reset your password:'=>'Siga el enlace a continuación para restablecer su contraseña:',
    'Password reset for '=>'Restablecimiento de contraseña para ',
    'There is no user with this email address.'=>'No hay usuario con esta dirección de correo electrónico.',
    'Account registration at '=>'Registro de cuenta en ',
    'Password reset token cannot be blank.'=>'El token de restablecimiento de contraseña no puede estar en blanco.',
    'Wrong password reset token.'=>'Token de restablecimiento de contraseña incorrecto.',
    'This username has already been taken.'=>'Este nombre de usuario ya ha sido tomado.',
    'This email address has already been taken.'=>'Esta dirección de correo electrónico ya ha sido tomada.',
    'Verify email token cannot be blank.'=>'Verifique que el token de correo electrónico no pueda estar en blanco.',
    'Wrong verify email token.'=>'Token de verificación de correo electrónico incorrecto.',
    ''=>'',
    
    //contact
    'Contact'=>'Contacto',
    'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.'=>'Si tiene consultas comerciales u otras preguntas, complete el siguiente formulario para contactarnos. Gracias.',
    'Verification Code'=>'Código de verificación',
    'Name'=>'Nombre',
    'Mail'=>'Correo electrónico',
    'Subject'=>'Asunto',
    'Body'=>'Mensaje',
    'Submit'=>'Enviar',


    //Menu
    'Setting'=>'Configuración',
    'Users'=>'Usuarios',
    'Permissions'=>'Permisos',
    'Ok'=>'De acuerdo',
    
    //User
    'Add'=>'Añadir',
    'Are you sure you want to delete this item?'=>'¿Está seguro de que quiere eliminar este elemento?',
    'Update User: '=>'Editar usuario: ',
    'Save'=>'Guardar',
    'Update'=>'Editar',
    'Delete'=>'Eliminar',
    'User List'=>'Lista de usuarios',
    'User'=>'Usuario',
    'Add New User'=>'Agregar usuario',
    'Firstname'=>'Nombres',
    'Lastname'=>'Apellido',
    'Profile picture'=>'Imagen de perfil',
    'Repeat Password'=>'Repetir contraseña',
    'Change Password'=>'Cambiar contraseña',
    'Change User Password: '=>'Cambiar contraseña usuario: ',


    'English'=>'Inglés',
    'Spanish'=>'Español',
     

    'View'=>'Ver',
    'Update'=>'Editar',
    'Clone'=>'Clonar',
    'Delete'=>'Eliminar',

    //pagination
    'First'=>'Primero',
    'first'=>'primero',
    'Last'=>'Ultimo',
    'last'=>'último',

    // Opciones
    'Yes' => 'Sí',
    'Female' => 'Femenino',
    'Male' => 'Masculino',

    'Update: {name}'=>'Editar: {name}',
    'Update'=>'Editar',
    'Select'=>'Seleccione',
 
    
];
